config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show]

  resources :charges, only: [:create, :destroy]

  
  resources :wikis do 
    resources :collaborations 
  end

  
  authenticated :user do
  	root "wikis#index", as: :authenticated_root
  end
  
  get 'about', to: 'welcome#about'

  root 'welcome#index'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :user
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend FriendlyId
  friendly_id :username, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis, dependent: :destroy

  has_many :collaborations

  has_many :wiki_collaborations, through: :collaborations, source: :wiki 
  
  has_many :charges

  enum role: {standard: 0, premium: 1, admin: 2}
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  default_scope { order('created_at DESC') } 
  has_many :collaborations
  has_many :users, through: :collaborations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
 
    charge = Stripe::Charge.create(
      customer: customer.id, 
      amount: 15_00, 
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    if charge.paid == true
      current_user.premium!
      current_user.charges.create(
        stripe_charge_id: charge.id,
        amount: charge.amount    
      )
      current_user.update(stripe_id: customer.id)
      flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
      redirect_to user_path(current_user) 
    end

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to user_path(current_user)
  end

  def destroy
    charge = Charge.find(params[:id])
    stripe_charge = Stripe::Charge.retrieve(charge.stripe_charge_id)

    if refund = stripe_charge.refunds.create(amount: 15_00)
      current_user.standard!
      charge.update(refunded: true)
      current_user.wikis.where(private: true).each do |wiki|
        wiki.update(private: false)
    end
      flash[:notice] = "You are now a lowly standard user"
    else
      flash[:alert] = 'Downgrade failed'
    end

    redirect_to user_path(current_user)
  end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.find(params[:user_id])
  	@collaboration = @wiki.collaborations.build(user_id: @user.id)
  	if @collaboration.save
      redirect_to root_path, notice: "Collaborator added"
    else
      flash[:alert] = "There was an error with your request"
      render :new
    end
  end


    def destroy
      @collaboration = Collaboration.find_by(wiki_id: params[:wiki_id], user_id: params[:user_id])

      if @collaboration.destroy
  	    flash[:notice] = "Collaboratoion was deleted"
      else
        flash.now[:alert] = "There was an error with your request"
      end
      redirect_to :back
    end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.friendly.find(params[:id])
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: 15_00
    }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @users = User.where.not(id: @wiki.user.id)
  end

  def new
  	@wiki = Wiki.new
    authorize @wiki
  end

  def create
  	@wiki = Wiki.new(wiki_params)
  	@wiki.user = current_user
  	if @wiki.save
      redirect_to root_path, notice: "Wiki was saved"
    else
      flash[:alert] = "There was an error with your request"
      render :new
    end
  end

  def edit
  	@wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
  	@wiki = Wiki.find(params[:id])
    authorize @wiki

  	if @wiki.update(wiki_params)
      flash[:notice] = "Wiki was successfully updated"
      redirect_to root_path, notice: "Wiki was updated"
    else
      flash.now[:alert] = "There was an error updated your wiki"
      render :edit
    end
  end

  def destroy
  	@wiki = Wiki.find(params[:id])

  	if @wiki.destroy
  	  flash[:notice] = "Wiki was deleted"
    else
      flash.now[:alert] = "There was an error with your request"
    end
    redirect_to wikis_path	
  end

  private

  def wiki_params
  	params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'redcarpet'
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/showdown/1.4.1/showdown.min.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <nav class="navbar navbar-inverse">

        <div class="col-md-3">
          <div class="navbar-header">
            <%= link_to "Home", root_path %>
            <%= link_to "About", about_path %>
          </div>
        </div>

        <div class="col-md-9">
          <div class="user-links pull-right">
            <% if user_signed_in? %>
              Signed in as: <strong><%= current_user.email %></strong> |
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <%= link_to 'Profile', user_path(current_user) %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
              <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
            <% end %>
          </div>
        </div>

      </nav>
    </div>
    <%= flash_messages %>
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <%= yield %>
    </div>
  </div>
</div> 

</body>
</html>

app/views/users/show.html.erb
<h1>User Profile</h1>
<p>Email: <%= @user.email %></p>
<%= link_to 'Home', root_path %> 

<% if @user == current_user && @user.premium? %>
  <h4>Downgrade to standard user</h4>
  <%= link_to "Downgrade account", charge_path(@user.charges.last), method: :delete, class: 'btn btn-danger' %>
<% elsif @user == current_user && @user.standard? %>
  <h4>Upgrade Premium Account</h4>
  <%= form_tag charges_path do %>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>
<% end %>

app/views/welcome/about.html.erb
<h1>About Us</h1>
<p>This is the descripton of what we will be building</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocopedia!</h1>
<p>This is the second project of the Bloc Program</p>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |w| %>
  <div class="form-group">
  <%= w.label :title %>
  <%= w.text_field :title %>
  </div>
  <div class="form-group">
  <%= w.label :body %>
  <%= w.text_area :body %>
  </div>
  <% if current_user.premium? || current_user.admin? %>
    <div class="form-group">
      <%= w.check_box :private %>
      <%= w.label :private %>
    </div>
  <% end %>
  <%= w.submit "save" %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Item</h1>
<%= render "form" %>

app/views/wikis/index.html.erb
<h1>All Current User's Wikis</h1>
<% if policy(Wiki.new).create? %>
  <%= link_to "New Wiki", new_wiki_path, class: "btn btn-inverse" %>
<% end %>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to (markdown_to_html wiki.title), wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="row">
  <div class="col-md-6">
    <%= render "form" %>
  </div>

  <h1>Preview</h1> 
  <div class="col-md-6" id="wiki-preview">
    
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown_to_html @wiki.body %></p>
  </div>
  <div class="col-md-4">
  <% if policy(@wiki).edit? %>
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
  <% end %>
  <% if policy(@wiki).destroy? %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this wiki?"} %>
  <% end %>
  </div>

  <div class="col-md-4">
    <% if policy(@wiki).add_collaborators? %>
      <h4>Add Collaborators</h4>
      <% @users.each do |user| %>
        <% if @wiki.users.include?(user) %>
          <%= link_to 'Remove Collaborator', wiki_collaboration_path(wiki_id: @wiki.id, user_id: user.id), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this collaborator?"}  %>
        <% else %>
          <p><%= user.email %></p>
          <%= link_to 'Add Collaborator', wiki_collaborations_path(wiki_id: @wiki.id, user_id: user.id), class: 'btn', method: :post %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>